config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root   'static_pages#home'
  get    '/inscrever',            to: 'usuarios#new'
  get    '/inscrever',            to: 'usuarios#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'
  get    '/faleconosco',          to: 'mensagens#new'
  post   '/faleconosco',          to: 'mensagens#create',       as: 'create_message'
  get    '/filter_by',            to: 'pombos#filter_by',       as: 'filter_by'
  get    '/familia',              to: 'pombos#familia'
  post   '/familia',              to: 'pombos#familia_create',  as: 'familia_create'
  
  resources :usuarios do
    member do
      get  :endereco
      post :salvar_endereco
      get  :editar_assinatura
      post :assinar
      get  :detalhar_assinatura
      post :cancelar_assinatura
      post :reenviar_email_ativacao
      post :alterar_tipo
      get  :visualizar_contrato
      post :aceitar_contrato
    end
    collection do
      get  :show_modal
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :pombals do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
    end
  end
  resources :tratamentos do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      get  :show_modal
      delete :destroy_pombal_tratamento
    end
  end
  
  resources :pombos do
    collection do
      get  :autocomplete
      get  :show_modal
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      post :create_titulo
      delete :destroy_titulo
    end
  end
  
  resources :competicaos do
    collection do
      get :atualiza_combo_clube
      get :modal_result
    end
    member do
      get :esquadrao
      get :esquadrao_order
    end
  end
  
  resources :provas do
    collection do
      get  :show_modal_result
      post :create_result
      delete :destroy_result
      get :recupera_desc
    end
    member do
      get  :filter_by
      get  :modal_nao_chegaram
      get  :preparar_importacao
      post  :importados
      get :modal_pp
      post :save_pp
    end
  end
  
  resources :equipes do
    member do
      get :show_modal
      post :assoc_pombo
      delete :desassoc_pombo
    end
  end
  
  resources :preparos
  resources :clubes
end

app/models/prova.rb
class Prova < ApplicationRecord
  belongs_to :competicao
  belongs_to :usuario
  
  has_many :resultados
  has_many :pombos, through: :resultados
  
  has_many :prova_preparos
  has_many :preparos, through: :prova_preparos
  
  scope :por_usuario, ->(u) { where(" exists ( select 1 from resultados r , pombos p where r.prova_id = provas.id and p.id = r.pombo_id and p.usuario_id = ?)", u) if u.present? }
end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController
  include MyModules::Util
  
  before_action :set_prova, only: [:show, :edit, :update, :destroy, :filter_by, :modal_nao_chegaram, :preparar_importacao, :importados, :preparo_prova]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :preparo_prova]
  before_action :bloquear
  
  def modal_nao_chegaram
    usuario = current_user
    @pombos = Pombo.por_usuario(usuario.id).por_equipe(Equipe.por_usuario(usuario.id).last).sem_resultado(@prova.id)
    respond_to do |format|
      format.js 
    end
  end
  
  def save_pp
    @pp = ProvaPreparo.new(pp_params)
    @pp.usuario_id = current_user.id
    if @pp.save
      msg = "#{t :label_preparo} #{t :msg_info_criado_com_sucesso}"
      respond_to do |format|
        format.js { flash.now[:success] =  msg}
      end
    else
      render :modal_pp
    end
    
  end
  
  def modal_pp
    @usr = current_user
    @desc = ""
    @prova = Prova.find(params[:id])
    @pp = ProvaPreparo.find_by(prova_id: @prova, usuario_id: @usr) || ProvaPreparo.new(prova_id: @prova.id, usuario_id: @usr)
    preparo = Preparo.find_by(id: @pp.preparo_id)
    @desc = preparo.descricao if preparo
    
    respond_to do |format|
      format.js 
    end
  end
  
  def recupera_desc
    @desc = Preparo.find_by(id: params[:id]).descricao || ''
    respond_to do |format|
      format.js
    end
  end
  
  def preparar_importacao
    @usuario = current_user
  end
  
  def importados
    @msgs = []
    @usuario = current_user
    if @usuario.admin?
      if usuario = Usuario.find_by(id: params[:id_usuario_sistema])
        id_usu = usuario.id
      else
        @msgs << "#{t :msg_erro_usuario_nao_encontrado_sistema} #{params[:id_usuario_sistema]}"
        render :preparar_importacao
        return
      end
    else
      id_usu = @usuario.id
    end
    msgs =  ResultadoImportado.import_file(params[:file], params[:id_usuario_filter], id_usu, @prova.id)
    if msgs.size == 0
      flash[:success] = "#{t :label_arquivo} #{t :msg_info_adiciado_com_sucesso}"
    else
      msgs.each do |m| 
        @msgs << "#{t m[:msg]} #{m[:campo]}"
      end
    end
    render :preparar_importacao
  end
  
  def filter_by
    @resultados = Resultado.por_prova(@prova).por_anilha(params[:anilha_filter])
    
    respond_to do |format|
      format.js 
    end
  end
  
  def show_modal_result
    @modal = params[:acao]
    if @modal == MODAL_PRV_RESUL
      
      @prova_modal = Prova.find(params[:id])
      
      if params[:r_id].blank?
        @result = Resultado.new
        @result.prova = @prova_modal
        @result.dhrestimada = Time.now.in_time_zone(current_user.fuso).strftime(mask_data_string_ruby)
        @result.dhroficial = Time.now.in_time_zone(current_user.fuso).strftime(mask_data_string_ruby)
      else
        @result = Resultado.find(params[:r_id])
      end
      @opcao_result = params[:opcao_result]
    elsif @modal == MODAL_PRV_ROTA
      @prova = Prova.find(params[:id])
      @usuario = current_user
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  def create_result
    
    id_result = params['resultado']['id']
    if id_result.present?
      @result = Resultado.find(id_result)
    else
      @result = Resultado.new()
      @result.pombo_id = params['resultado']['pombo_id']
      @result.prova_id = params['resultado']['prova_id']
    end
    
    
    @result.usuario_id = current_user.id
    
    if params[:opcao_result] == 'P'
      @result.dhrestimada = date_transform('dhrestimada')
    else
      @result.dhroficial = date_transform('dhroficial')
      @result.posicao = params['resultado']['posicao']
      @result.pontos = params['resultado']['pontos']
      @result.dist_oficial = params['resultado']['dist_oficial']
      @result.veloc_oficial = params['resultado']['veloc_oficial']
    end
    
    if @result.save
      @prova_modal = @result.prova
      redirect_to @prova_modal
      flash[:success] = t(:label_marcacao) + " " + t(:msg_info_criado_com_sucesso)
    else
      render :show_modal_result
    end
    
  end
  
  def destroy_result
    result = Resultado.find(params[:id])
    @prova = result.prova
    result.destroy
    
    redirect_to @prova
    flash[:success] = t(:label_marcacao) + " " + t(:msg_info_excluido_com_sucesso)
  end

  # GET /provas
  def index
    @provas = Prova.all.order(dtsolta: :desc)
  end

  # GET /provas/1
  def show
    @resultados = @prova.resultados
    if Resultado.por_prova(@prova).oficial.count > 0
      params[:lista_result] = 'O'
    else
      params[:lista_result] = 'P'
    end
  end
  
  # GET /provas/new
  def new
    @prova = Prova.new
    if params['competicao_id'].present?
      @prova.competicao_id = params['competicao_id']
    end
  end

  # GET /provas/1/edit
  def edit
    @prova.usuario = current_user
  end

  # POST /provas
  # POST /provas.json
  def create
    @prova = Prova.new(prova_params)
    @prova.usuario = current_user
    @prova.update_attributes(lat: dms_to_degrees(@prova.lat_deg, @prova.lat_min, @prova.lat_seg, @prova.lat_card), 
                              lng: dms_to_degrees(@prova.lng_deg, @prova.lng_min, @prova.lng_seg, @prova.lng_card))
    
    if @prova.save
      redirect_to @prova
      flash[:success] = t(:label_prova) + " " + t(:msg_info_criado_com_sucesso)
    else
      render :new
    end
  end

  # PATCH/PUT /provas/1 
  def update
    if @prova.update(prova_params)
      
      @prova.update_attributes(lat: dms_to_degrees(@prova.lat_deg, @prova.lat_min, @prova.lat_seg, @prova.lat_card), 
                              lng: dms_to_degrees(@prova.lng_deg, @prova.lng_min, @prova.lng_seg, @prova.lng_card))
      redirect_to @prova
      flash[:success] = t(:label_prova) + " " + t(:msg_info_atualizado_com_sucesso)
    else
      render :edit
    end
  end

  # DELETE /provas/1
  def destroy
    @prova.resultados.each do |r|
      r.destroy
    end
    
    @prova.destroy
    redirect_to provas_url
    flash[:success] = t(:label_prova) + " " + t(:msg_info_excluido_com_sucesso) 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prova
      @prova = Prova.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prova_params
      params.require(:prova).permit(:nome, :dtsolta, :tipo, :competicao_id, :lat, :lng, :usuario_id, :lat_card, :lat_deg, :lat_min, :lat_seg, :lng_card, :lng_deg, :lng_min, :lng_seg)
    end
    
    def result_params
      params.require(:resultado).permit(:dhrestimada, :dhroficial, :posicao, :pontos, :pombo_id, :prova_id, :id)
    end
    
    def pp_params
      params.require(:prova_preparo).permit(:preparo_id, :prova_id)
    end
    
    def mask_data_string_ruby
      if session[:locale] == "en"
        '%m/%d/%Y %H:%M:%S%z'
      else
        '%d/%m/%Y %H:%M:%S%z'
      end
    end
    
    def bloquear
      usr = current_user
      msg =  bloqueio(usr, BLOQUEIO_PAGTO)
      if msg != ''
        flash[:danger] = t msg
        redirect_to detalhar_assinatura_usuario_path(usr)
      end
    end
    
    def date_transform(nome)
      Time.zone.parse(
        params['resultado']["#{nome}(1i)"] + '-' +
        params['resultado']["#{nome}(2i)"] + '-' +
        params['resultado']["#{nome}(3i)"] + ' ' +
        params['resultado']["#{nome}(4i)"] + ':' +
        params['resultado']["#{nome}(5i)"] + ':' +
        params['resultado']["#{nome}(6i)"]
      )
      
    end
end

app/helpers/provas_helper.rb
module ProvasHelper
  def class_pill(proprio_result, default)
    if proprio_result 
      'primary'
    else
      default
    end
  end
end

app/views/provas/_desc_text_area.html.erb
<div class="form-group">
  <%= text_area_tag :desc, @desc, class: 'form-control', readonly: true %>
</div>

app/views/provas/_form.html.erb
<%= form_for(prova) do |f| %>
  <%= render 'shared/error_messages', obj: prova %>
  
  <%= f.hidden_field :usuario_id %>
  
  <div class="form-group">
    <%= f.label t :label_competicao %>
    <%= f.select(:competicao_id, competicao_for_select, {include_blank: true} , {class: 'form-control', required: true }) %>
  </div>
  
  <div class="form-group">
    <%= f.label t :label_nome %>
    <%= f.text_field :nome, class: 'form-control', required: true, size: 100 %>
  </div>
  
  <div class="form-group">
    <%= f.label t :label_tipo %>
    <%= f.select(:tipo, tipo_prova_for_select, {include_blank: true} , {class: 'form-control', required: true }) %>
  </div>
  
  <div class="form-group">
    <%= f.label t :label_horario_solta %>
    <%= f.datetime_field :dtsolta, as: :date, value: f.object.try(:strftime, mask_datahora_sem_segundos), class: 'data_input_altura form-control', required: true %>
  </div>
  
  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  
  <div class="form-group">
    <%= f.label t :label_latitude %>
    <div class="row linha-1-4">
      <div class="form-group col-sm-3">
        <%= f.select(:lat_card, options_for_select(["S", "N"], "S"), {include_blank: false}, {class: 'form-control'}) %>
      </div>
      <div class="form-group col-sm-3">
        <%= f.number_field :lat_deg, value: number_with_precision(f.object.lat_deg, precision: 0), class: 'form-control', required: true, min: -90, max: 90, step: 1 %>
      </div>
      <div class="form-group col-sm-3">
        <%= f.number_field :lat_min, value: number_with_precision(f.object.lat_min, precision: 0), class: 'form-control', required: true, min: 0, max: 99, step: 1 %>
      </div>
      <div class="form-group col-sm-3">
        <%= f.number_field :lat_seg, class: 'form-control', required: true, min: 0, max: 999, step: 0.1 %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label t :label_longitude %>
    <div class="row linha-1-4">
      <div class="form-group col-sm-3">
        <%= f.select(:lng_card, options_for_select(["W", "E"], "W"), {include_blank: false}, {class: 'form-control'}) %>
      </div>
      <div class="form-group col-sm-3">
        <%= f.number_field :lng_deg, value: number_with_precision(f.object.lng_deg, precision: 0), class: 'form-control', required: true, min: -180, max: 180, step: 1 %>
      </div>
      <div class="form-group col-sm-3">
        <%= f.number_field :lng_min, value: number_with_precision(f.object.lng_min, precision: 0), class: 'form-control', required: true, min: 0, max: 99, step: 1 %>
      </div>
      <div class="form-group col-sm-3">
        <%= f.number_field :lng_seg, class: 'form-control', required: true, min: 0, max: 999, step: 0.1 %>
      </div>
    </div>
  </div>
  
  <div class="form-group">
    <%= link_to show_modal_result_provas_path(acao: MODAL_PRV_COORD),  id: "link_modal_mapa", class: botao_link, remote: true do %>
      <span class="fa fa-globe"></span> <%= t :label_coordenadas %>
    <% end %>
  </div>
  
  <%= f.submit yield(:button_text), class: botao_estilo %>
  <br /><br />
  
<% end %>


<div id="modal">
</div>

app/views/provas/_lista_resultados.html.erb
<div id="lista_result" class="list-group panel-group">
  
  
  <% @resultados.parcial.sort_by{|x| velocidade_mm(@prova, x.dhrestimada, x.usuario_id ) }.reverse.each_with_index do |r, index| %>
    <% duracao_min = r.dhrestimada.blank? ? 0 : (r.dhrestimada - @prova.dtsolta)/1.minutes  %>
    <% usuario_nome = (r.usuario.nome_time.blank? ? r.usuario.nome : r.usuario.nome_time) if r.usuario != nil %>
    
    <div class="list-group-item card">
      <div class="card-header row linha-1-4">
        <div class="col-sm-12">
          <small class="form-text">
            <a data-toggle="collapse" href="#collapse<%= "#{r.id}" %>">
              <strong><span class="badge badge-pill badge-<%= class_pill(visivel(r.usuario_id), 'danger') %>"><%= "#{index+1}º" %></span></strong>
            </a>
            <a data-toggle="collapse" href="#collapse<%= "#{r.id}" %>">
              <strong><%= "#{r.pombo.anilha}" %></strong> 
            </a>
            <%= "#{number_with_precision(velocidade_mm(@prova, r.dhrestimada, r.usuario_id ), precision: 2)}M/min"  %>
            <%= r.dhrestimada.strftime("%H:%M:%S") if r.dhrestimada.present? %>
            <%= "- #{usuario_nome}" %>
          </small>
        </div>
        
      </div>
      <div class="collapse" id="collapse<%= "#{r.id}" %>">
        <div class="card-body">
          <div class="row linha-1-4">
            <div class="col-sm-4">
              <small class="form-text">
                <strong><%= t :label_velocidade_media %></strong>: <%= "#{number_with_precision(velocidade_mm(@prova, r.dhrestimada, r.usuario_id ), precision: 2)}M/min"  %>
              </small>
            </div>
            <div class="col-sm-3">
              <small class="form-text">
                <strong><%= t :label_hora_estimada %></strong>: <%= r.dhrestimada.strftime("%H:%M:%S") if r.dhrestimada.present? %>
              </small>
            </div>
            <div class="col-sm-2">
              <small class="form-text">
                <strong><%= t :label_tempo %></strong>: <%= "#{(duracao_min/1.minutes).to_i}h#{(duracao_min%1.minutes).to_i}min"  %>
              </small>
            </div>
            <div class="col-sm-3">
              <small class="form-text">
                <strong><%= t :label_velocidade_media %> Km/h</strong>: <%= "#{number_with_precision(calcula_distancia_km_por_usr(@prova, r.usuario_id)/ duracao_min * 1.minutes, precision: 2)}Km/h"  %>
              </small>
            </div>
            
          </div>
          <div class="row linha-1-4">
            <div class="col-sm-12">
              <% if logged_in? && visivel(r.usuario_id) %>
              
                <%= link_to show_modal_result_provas_path(id: @prova.id, r_id: r.id, acao: MODAL_PRV_RESUL, opcao_result: 'P'), class: botao_link, remote: true,
                           :title => t(:label_alterar_compl, compl: t(:label_chegada)), :rel => 'tooltip', "data-placement" => "bottom" do %>
                  <span class="fa fa-flag"></span>
                <% end %>
                
                <%= link_to destroy_result_provas_path(id: r.id), method: :delete, data: { confirm: t(:msg_quest_apagar_resultado) }, class: botao_link, remote: true, 
                           :title => t(:label_excluir), :rel => 'tooltip', "data-placement" => "bottom" do %>
                  <span class="fa fa-trash"></span>
                <% end %>
                
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
      
  <% end %>
</div>

app/views/provas/_modal.html.erb
<div id="modal_result_partial" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-header bg-light">
        <h4 class="modal-title"><%= "#{t :label_prova} #{@prova_modal.nome} - #{t("label_tipo_prova_#{@prova_modal.tipo}")}"  %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <div class="modal-body">
        <div id="modal_msg"></div>
        <div>
          <%= form_for(@result, url: create_result_provas_path, method: "post", remote: true) do |f| %>
            <%= render 'shared/error_messages', obj: @result %>
            
            <%= f.hidden_field :prova_id, value: @prova_modal.id %>
            <%= f.hidden_field :id %>
            
            <div class="form-group">
              <%= f.label t :label_pombo %>
              <%= f.select(:pombo_id, pombo_for_select, {include_blank: true} , {class: 'form-control', required: true }) %>
            </div>
            
            <div class="form-group">
              <div id="opcoes">
                <div class="form-check-inline">
                  <label class="form-check-label">
                    <%= radio_button_tag 'opcao_result', 'P', params[:opcao_result] == 'P', class: "form-check-input" %><%= t(:label_parcial)%>
                  </label>
                </div>
                <div class="form-check-inline">
                  <label class="form-check-label">
                    <%= radio_button_tag 'opcao_result', 'O', params[:opcao_result] == 'O', class: "form-check-input" %><%= t(:label_oficial)%>
                  </label>
                </div>
                <br />
              </div>
            </div>
            
            
            <div class="form-group" id="parcial">
              <%= f.label t :label_hora_estimada %>
              <div class="form-group">
                <%= f.datetime_select :dhrestimada, 
                  { include_seconds: true, use_short_month: true, with_css_classes: true}, 
                  {class: "form-control-sm" } %>
              </div>
            </div>
            
            <div id="oficial">
              <div class="form-group">
                <%= f.label t :label_hora_oficial %>
                <div class="form-group">
                  <%= f.datetime_select :dhroficial, 
                    { include_seconds: true, use_short_month: true, with_css_classes: true}, 
                    {class: "form-control-sm" } %>
                </div>
              </div>
              
              <div class="form-group">
                <%= f.label t :label_posicao %>
                <%= f.number_field :posicao, min: 1, max: 9999, step: 1, class: 'form-control' %>
              </div>
              
              <div class="form-group">
                <%= f.label t :label_pontos %>
                <%= f.number_field :pontos, class: 'form-control', min: 1, max: 9999, step: 0.1 %>
              </div>
              
              <div class="form-group">
                <%= f.label t :label_distancia %>
                <%= f.number_field :dist_oficial, class: 'form-control', min: 1, max: 99999999, step: 0.001 %>
              </div>
              
              <div class="form-group">
                <%= f.label t :label_velocidade %>
                <%= f.number_field :veloc_oficial, class: 'form-control', min: 1, max: 99999999, step: 0.001 %>
              </div>
              
            </div>
            
            <%= f.submit (@result.id ? t(:label_alterar) : t(:label_adicionar)), class: botao_estilo %>
            
          <% end %>
        </div>
        
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><%= t(:label_fechar) %></button>
      </div>
      
    </div>
  </div>
</div>

<script>
  $(function() {
    $( "<div id='quebrou-linha'><br />" ).insertBefore( ".hour" );
  });
  
</script>

app/views/provas/_modal_preparo_prova.html.erb
<div id="modal_prep_prova" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header bg-light">
        <h5 class="modal-title"><%= "#{@prova.competicao.nome.upcase} - #{@prova.competicao.ano}" %></h5>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <div class="modal-body">
        <div id="modal_msg"></div>
        
        <div class="form-group">
          <small class="form-text">
            <strong><%= "#{t(:label_prova).upcase} #{@prova.nome} " %><%= t("label_tipo_prova_#{@prova.tipo}").upcase %> </strong>
          </small>
        </div>
        <%= form_for(@pp, url: save_pp_prova_path, method: "post", remote: true) do |f| %>
          <%= render 'shared/error_messages', obj: @titulo %>
          
          <div class="form-group">
            <%= f.label :preparo_id, t(:label_preparo) %>
            <%= f.select(:preparo_id, preparo_for_select, {include_blank: true}, {class: 'form-control', required: true }) %>
          </div>
          
          <div id="textarea_desc">
            <%= render 'desc_text_area' %>
          </div>
          
          <%= f.hidden_field :prova_id, value: @pp.prova_id %>
          
          <%= f.submit t(:label_salvar), class: botao_estilo %>
        <% end %>
        
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><%= t(:label_fechar) %></button>
      </div>
    </div>
  </div>
</div>

<script>
  $('select').on('change', function() {
    var val = this.value;
    $.ajax({
      url: "/provas/recupera_desc/",
      type: "GET",
      data: {
        id: val
      }
    });
    
  });
  
</script>

app/views/provas/edit.html.erb
<% provide(:title, t(:label_atualizar)) %>
<% provide(:button_text, t(:label_atualizar)) %>
<% provide :head_tags %>

<h4><strong><%= "#{t :label_atualizar}  #{t :label_prova}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', prova: @prova %>
  </div>
</div>

<%= link_to provas_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t :label_cancelar %>
<% end %>

app/views/provas/filter_by.js.erb
if ($("#lista_result_O").is(':checked')) {
  $("#result_lista").html("<%= j render partial: 'lista_resultados_oficial' %>");
}
else {
  $("#result_lista").html("<%= j render partial: 'lista_resultados' %>");
}

app/views/provas/index.html.erb
<% provide(:title, t(:label_lista_provas)) %>
<h4><strong><%= t :label_lista_provas %></strong></h4>

<%= link_to new_prova_path, class: botao_link do %>
  <span class="fa fa-plus"></span> <%= "#{t :label_cadastrar} #{t :label_prova}" %>
<% end %>
<br /><br />

<div id="lista_pombal" class="list-group">
  <% if @provas != nil %>
    <% @provas.each do |prova| %>
      <div class="list-group-item">
        <div class="row linha-1-4">
          <div class="col-sm-12">
            <strong><%= "#{prova.competicao.nome}-#{prova.competicao.ano}" %></strong> 
          </div>
        </div>
        <div class="row linha-1-4">
          <div class="col-sm-8">
            <%= link_to prova do %><%= prova.nome %> - <%= t("label_tipo_prova_#{prova.tipo}") %><% end %>
          </div>
          <div class="col-sm-4">
            <strong><%= t :label_horario_solta %></strong>: <%= prova.dtsolta.strftime(mask_datahora_sem_segundos) %>
          </div>
        </div>
        <div class="row linha-2-0">
          <div class="col-sm-12">
            <% if autor_info(prova.usuario) %>
              <%= link_to edit_prova_path(prova), class: botao_link, :title => t(:label_editar), :rel => 'tooltip', "data-placement" => "bottom" do %>
                <span class="fa fa-pencil"></span>
              <% end %>
              <%= link_to prova, method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, :title => t(:label_excluir), :rel => 'tooltip', "data-placement" => "bottom" do %>
                <span class="fa fa-trash"></span>
              <% end %>
            <% end %>
            <%= link_to show_modal_result_provas_path(id: prova.id, acao: MODAL_PRV_RESUL, opcao_result: 'P'), class: botao_link, remote: true do %>
              <span class="fa fa-flag"></span> <%= t :label_informar_chegada %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<br>
<div id="modal_result"></div>

app/views/provas/modal_nao_chegaram.js.erb
$('#modal_result').html("<%= j render 'modal_pombos_ausentes' %>");
$('#modal_pombos_ausentes').modal('show');

app/views/provas/modal_pp.js.erb
$('#modal_result').html("<%= j render 'modal_preparo_prova' %>");
$('#modal_prep_prova').modal('show');

app/views/provas/new.html.erb
<% provide(:title, "#{t :label_cadastrar} #{t :label_prova}") %>
<% provide(:button_text, t(:label_salvar)) %>
<% provide :head_tags %>

<h4><strong><%= "#{t :label_cadastrar} #{t :label_prova}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', prova: @prova %>
  </div>
</div>

<%= link_to provas_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/provas/recupera_desc.js.erb
$("#textarea_desc").empty()
  .append("<%= j render partial: 'desc_text_area' %>");