config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root   'static_pages#home'
  get    '/inscrever',            to: 'usuarios#new'
  get    '/inscrever',            to: 'usuarios#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'
  get    '/faleconosco',          to: 'mensagens#new'
  post   '/faleconosco',          to: 'mensagens#create',       as: 'create_message'
  get    '/filter_by',            to: 'pombos#filter_by',       as: 'filter_by'
  get    '/familia',              to: 'pombos#familia'
  post   '/familia',              to: 'pombos#familia_create',  as: 'familia_create'
  
  resources :usuarios do
    member do
      get  :endereco
      post :salvar_endereco
      get  :editar_assinatura
      post :assinar
      get  :detalhar_assinatura
      post :cancelar_assinatura
      post :reenviar_email_ativacao
      post :alterar_tipo
      get  :visualizar_contrato
      post :aceitar_contrato
    end
    collection do
      get  :show_modal
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :pombals do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
    end
  end
  resources :tratamentos do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      get  :show_modal
      delete :destroy_pombal_tratamento
    end
  end
  
  resources :pombos do
    collection do
      get  :autocomplete
      get  :show_modal
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      post :create_titulo
      delete :destroy_titulo
    end
  end
  
  resources :competicaos do
    collection do
      get :atualiza_combo_clube
      get :modal_result
    end
    member do
      get :esquadrao
      get :esquadrao_order
    end
  end
  
  resources :provas do
    collection do
      get  :show_modal_result
      post :create_result
      delete :destroy_result
      get :recupera_desc
    end
    member do
      get  :filter_by
      get  :modal_nao_chegaram
      get  :preparar_importacao
      post  :importados
      get :modal_pp
      post :save_pp
    end
  end
  
  resources :equipes do
    member do
      get :show_modal
      post :assoc_pombo
      delete :desassoc_pombo
    end
  end
  
  resources :preparos
  resources :clubes
end

app/models/equipe.rb
class Equipe < ApplicationRecord
  belongs_to :usuario
  
  has_and_belongs_to_many :pombos
  
  scope :por_usuario, ->(par) {where("usuario_id = ?", par) if par.present? }
  
end

app/controllers/equipes_controller.rb
class EquipesController < ApplicationController
  before_action :set_equipe, only: [:show, :edit, :update, :destroy, :show_modal, :assoc_pombo, :desassoc_pombo]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :show]
  before_action :correct_user,   only: [:edit, :update, :show, :destroy]
  before_action :bloquear
  
  def show_modal
    @pombo = Pombo.new
    respond_to do |format|
      format.js
    end
  end
  
  def assoc_pombo
    @ok = true
    pombos = Pombo.por_anilha(params["pombo"]["anilha"]).por_usuario(current_user)
    if pombos.count > 0
      @pombo = pombos.first
      if @pombo.equipes.any?
        @ok = false
        tipo_alerta = 'danger'
       msg = t :msg_info_presente_time
      else
        @equipe.pombos << @pombo
        tipo_alerta = 'success'
        msg = "#{t :label_pombo} #{t :msg_info_adiciado_com_sucesso}"
      end
    else
      @ok = false
      tipo_alerta = 'danger'
      msg = t :msg_erro_anilha_nao_encontrada
    end
    
    respond_to do |format|
      format.js { flash.now[tipo_alerta] =  msg}
    end
  end
  
  def desassoc_pombo
    pombo = Pombo.find(params["pombo_id"])
    @equipe.pombos.delete(pombo)
    @tela = params['tela']
    
    respond_to do |format|
      format.js { flash.now[:success] = t(:label_pombo) + " " + t(:msg_info_removido_com_sucesso) }
    end
  end

  def index
    @equipes = Equipe.por_usuario(current_user)
    if @equipes.count == 0
      redirect_to new_equipe_url
    end
  end

  def show
  end

  def new
    @equipe = Equipe.new
  end

  def edit
  end

  def create
    @equipe = Equipe.new(equipe_params)
    @equipe.usuario = current_user
    
    if @equipe.save
      redirect_to equipes_path
      flash[:success] = t(:label_time) + " " + t(:msg_info_criado_com_sucesso)
    else
      render :new
    end
  end

  def update
    if @equipe.update(equipe_params)
      redirect_to @equipe
      flash[:success] = t(:label_time) + " " + t(:msg_info_atualizado_com_sucesso)
    else
      render :edit
    end
  end

  def destroy
    @equipe.pombos.delete_all
    @equipe.destroy
    redirect_to equipes_url
    flash[:success] = t(:label_time) + " " + t(:msg_info_excluido_com_sucesso)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipe
      @equipe = Equipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipe_params
      params.require(:equipe).permit(:nome)
    end
    
    def correct_user
      @equipe = current_user.equipes.find_by(id: params[:id])
      if @equipe.nil?
        flash[:danger] = t(:msg_erro_acao_nao_permitida)
        redirect_to usuario_path(current_user)
      end
    end
    
    def bloquear
      usr = current_user
      msg =  bloqueio(usr, BLOQUEIO_PAGTO)
      if msg != ''
        flash[:danger] = t msg
        redirect_to detalhar_assinatura_usuario_path(usr)
      end
    end
end

app/helpers/equipes_helper.rb
module EquipesHelper
end

app/views/equipes/_form.html.erb
<%= form_for(equipe) do |f| %>

  <%= render 'shared/error_messages', obj: equipe %>
  
  <div class="form-group">
    <%= f.label t :label_nome %>
    <%= f.text_field :nome, class: 'form-control', required: true, size: 50 %>
  </div>
  
  <%= f.submit yield(:button_text), class: botao_estilo %>
  <br /><br />
  
<% end %>

app/views/equipes/_lista.html.erb
<table class="table table-hover" id="tabpombosindex" >
  <thead>
    <tr>
      <th><%= t(:label_anilha) %></th>
      <th><%= t(:label_sexo) %></th>
     </tr>
  </thead>
      
  <tbody>
    <% @equipe.pombos.order('anilha').each do |pombo| %>
      <tr>
        <td>
          <%= link_to desassoc_pombo_equipe_path(id: @equipe.id, pombo_id: pombo.id, tela: 'index'), method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, remote: true, :title => t(:label_remover), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-trash"></span>
          <% end %>
          <%= pombo.anilha %>
        </td>
        <td><%= pombo.sexo == "F" ? t(:label_sexo_F) : t(:label_sexo_M) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/equipes/_lista_pombos.html.erb
<table class="table table-hover" id="tabpombos" >
  <thead>
    <tr>
      <th><%= t(:label_anilha) %></th>
      <th><%= t(:label_sexo) %></th>
     </tr>
  </thead>
      
  <tbody>
    <% @equipe.pombos.order('anilha').each do |pombo| %>
      <tr>
        <td>
          <%= link_to desassoc_pombo_equipe_path(id: @equipe.id, pombo_id: pombo.id, tela: 'modal'), method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, remote: true, :title => t(:label_remover), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-trash"></span>
          <% end %>
          <%= pombo.anilha %>
        </td>
        <td><%= pombo.sexo == "F" ? t(:label_sexo_F) : t(:label_sexo_M) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/equipes/_modal.html.erb
<!-- https://www.mirceasamuila.com/posts/bootstrap-modals-in-rails -->
<div id="modal_equipe_partial" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header bg-light">
        <h4 class="modal-title"><%= "#{t :label_time} #{@equipe.nome} "%></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <div class="modal-body">
        <div id="modal_msg"></div>
                            
        <%= form_for(@pombo, url: assoc_pombo_equipe_path, method: "post", remote: true) do |f| %>
          <%= render 'shared/error_messages', obj: @pombo %>
          
          <div class="form-group">
            <%= f.label t :label_anilha %>
            <%= f.text_field :anilha, size: 12, class: 'form-control', required: true, autofocus: true %>
          </div>
          
          <%= f.submit t(:label_adicionar), class: botao_estilo %>
          
        <% end %>
        
        <br />
        <h5><%= t :label_lista_pombos %></a></h5>
      
        <div class="card-body">
          <%= render 'lista_pombos' %>
        </div>
          
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><%= t(:label_fechar) %></button>
      </div>
    </div>
  </div>
</div>

app/views/equipes/assoc_pombo.js.erb
$('#tabpombos').empty()
  .append("<%= j render partial: 'lista_pombos' %>");

$('#tabpombosindex').empty()
  .append("<%= j render partial: 'lista' %>");

<% if @ok %>
  $("#pombo_anilha").val('');
  $("#modal_msg").addClass("alert alert-success");
  $("#modal_msg").html("<%= flash[:success] %>");
<% else %>
  $("#modal_msg").addClass("alert alert-danger");
  $("#modal_msg").html("<%= flash[:danger] %>");
<% end %>

app/views/equipes/desassoc_pombo.js.erb
$('#tabpombos').empty()
  .append("<%= j render partial: 'lista_pombos' %>");

$('#tabpombosindex').empty()
  .append("<%= j render partial: 'lista' %>");

<% if @tela == 'modal'%>
  $("#modal_msg").addClass("alert alert-success");
  $("#modal_msg").html("<%= flash[:success] %>");
<% else %>
  $("#index_msg").addClass("alert alert-success");
  $("#index_msg").html("<%= flash[:success] %>");
<% end %>

app/views/equipes/edit.html.erb
<% provide(:title, t(:label_atualizar)) %>
<% provide(:button_text, t(:label_atualizar)) %>

<h4><strong><%= "#{t :label_atualizar}  #{t :label_time}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', equipe: @equipe %>
  </div>
</div>

<%= link_to equipes_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/equipes/index.html.erb
<% provide(:title, t(:label_time)) %>

<div id="index_msg"></div>
<h4><strong><%= t :label_time %></strong></h4>
<!--
%= link_to new_equipe_path, class: botao_link do %
  <span class="fa fa-plus"></span> %= "#{t :label_cadastrar} #{t :label_time}" %
% end %
-->

<div id="lista_eqps" class="list-group">
  <% @equipes.each do |equipe| %>
    <div class="list-group-item">
      <div class="row linha-1-4">
        <div class="col-sm-5">
          <strong><%= t(:label_nome) %></strong>: <%= equipe.nome %>
        </div>
      </div>
      <div class="row linha-2-0">
        <div class="col-sm-12">
          <%= link_to edit_equipe_path(equipe), class: botao_link, :title => t(:label_editar), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to show_modal_equipe_path(equipe),  class: botao_link, remote: true, :title => "#{t(:label_adicionar_compl, compl: t(:label_pombo))}", :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-plus-circle"></span>
          <% end %>
          <%= link_to equipe, method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, :title => t(:label_excluir), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-trash"></span>
          <% end %>
        </div>
      </div>
      
      <div id="lista_time">
        <% @equipe = equipe %>
        <%= render 'lista' %>
      </div>

    </div>
  <% end %>
</div>

<br>
<div id="modal">
</div>

app/views/equipes/new.html.erb
<% provide(:title, "#{t :label_cadastrar} #{t :label_time}") %>
<% provide(:button_text, t(:label_salvar)) %>

<h4><strong><%= "#{t :label_cadastrar} #{t :label_time}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', equipe: @equipe %>
  </div>
</div>

<%= link_to equipes_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/equipes/show.html.erb
<% provide(:title, @equipe.nome) %>

<p>
  <h4>
    <strong><%= t :label_time %></strong>: <%= @equipe.nome %>
  </h4>
</p>

<h4><%= "#{t :label_pombo}s" %></h4>

<div id="lista_time">
  <%= render 'lista' %>
</div>

<%= link_to edit_equipe_path(@equipe), class: botao_link, :title => t(:label_editar), :rel => 'tooltip', "data-placement" => "bottom" do %>
  <span class="fa fa-pencil"></span>
<% end %>

<%= link_to show_modal_equipe_path(@equipe),  class: botao_link, remote: true, :title => "#{t(:label_adicionar_compl, compl: t(:label_pombo))}", :rel => 'tooltip', "data-placement" => "bottom" do %>
  <span class="fa fa-plus-circle"></span>
<% end %>

<%= link_to equipes_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:label_voltar) %>
<% end %>

<div id="modal">
</div>

app/views/equipes/show_modal.js.erb
$("#modal").html("<%= j render 'modal' %>");
$('#modal_equipe_partial').modal('show');