config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root   'static_pages#home'
  get    '/inscrever',            to: 'usuarios#new'
  get    '/inscrever',            to: 'usuarios#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'
  get    '/faleconosco',          to: 'mensagens#new'
  post   '/faleconosco',          to: 'mensagens#create',       as: 'create_message'
  get    '/filter_by',            to: 'pombos#filter_by',       as: 'filter_by'
  get    '/familia',              to: 'pombos#familia'
  post   '/familia',              to: 'pombos#familia_create',  as: 'familia_create'
  
  resources :usuarios do
    member do
      get  :endereco
      post :salvar_endereco
      get  :editar_assinatura
      post :assinar
      get  :detalhar_assinatura
      post :cancelar_assinatura
      post :reenviar_email_ativacao
      post :alterar_tipo
      get  :visualizar_contrato
      post :aceitar_contrato
    end
    collection do
      get  :show_modal
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :pombals do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
    end
  end
  resources :tratamentos do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      get  :show_modal
      delete :destroy_pombal_tratamento
    end
  end
  
  resources :pombos do
    collection do
      get  :autocomplete
      get  :show_modal
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      post :create_titulo
      delete :destroy_titulo
    end
  end
  
  resources :competicaos do
    collection do
      get :atualiza_combo_clube
      get :modal_result
    end
    member do
      get :esquadrao
      get :esquadrao_order
    end
  end
  
  resources :provas do
    collection do
      get  :show_modal_result
      post :create_result
      delete :destroy_result
      get :recupera_desc
    end
    member do
      get  :filter_by
      get  :modal_nao_chegaram
      get  :preparar_importacao
      post  :importados
      get :modal_pp
      post :save_pp
    end
  end
  
  resources :equipes do
    member do
      get :show_modal
      post :assoc_pombo
      delete :desassoc_pombo
    end
  end
  
  resources :preparos
  resources :clubes
end

app/models/pombo.rb
class Pombo < ApplicationRecord
  
  belongs_to :cor
  belongs_to :usuario
  has_and_belongs_to_many :pombals
  has_and_belongs_to_many :equipes
  
  has_many :aplicacaos
  has_many :tratamentos, through: :aplicacaos
  
  has_many :titulos
  
  has_many :resultados
  has_many :provas, through: :resultados
  
  before_validation   :pai_eh_macho, :mae_eh_femea
  before_save :ajuste_strings
  
  validates :anilha, length: { maximum: 10 }
  validates :nome,   presence: false, length: { maximum: 50 }
  validates :dtnasc, presence: false
  
  #validates :sexo,   presence: true, format: { 
  #     with: /^(F|M)$/ ,
  #     message: 'precisa ser F/M',
  #     multiline: true
  # }
  
  scope :por_anilha, ->(par) { where("anilha = ?", par.upcase) if par.present? }
  scope :por_pai, ->(nome_par, anilha_par) { where("pai_id = (select p2.id from pombos p2 where pombos.usuario_id = p2.usuario_id and (p2.nome LIKE ? or p2.anilha LIKE ?))", nome_par.capitalize + '%', anilha_par.upcase + '%') if nome_par.present? }
  scope :por_mae, ->(nome_par, anilha_par) { where("mae_id = (select p2.id from pombos p2 where pombos.usuario_id = p2.usuario_id and (p2.nome LIKE ? or p2.anilha LIKE ?))", nome_par.capitalize + '%', anilha_par.upcase + '%') if nome_par.present? }
  scope :esta_vivo, ->(par) { where("vivo = ?", par) if par.present? }
  scope :por_usuario, ->(par) {where("usuario_id = ?", par) if par.present? }
  scope :anilha_like, ->(par) { where("anilha LIKE ?", "%#{par.upcase}%") if par.present? }
  scope :em_tratamento, ->(p, t) { where(" exists ( select 1 from pombal_tratamentos pt, aplicacaos a where a.pombo_id = pombos.id and pt.id = a.pt_id and pt.pombal_id = ? and pt.tratamento_id = ?)", p, t) if p.present? }
  scope :por_equipe, ->(par) { where(" exists ( select 1 from equipes_pombos ep where ep.pombo_id = pombos.id and ep.equipe_id = ? )", par) if par.present? }
  scope :sem_resultado, ->(par) { where(" not exists (select 1 from resultados r where r.pombo_id = pombos.id and r.prova_id = ? )", par) if par.present? }
  
  #validates_with SexoValidator
  
  def pai
    if self.pai_id != nil
      begin
        Pombo.find(self.pai_id)
      rescue ActiveRecord::RecordNotFound 
        nil
      end
    else
      nil
    end
  end
  
  def mae
    if self.mae_id != nil
      begin
        Pombo.find(self.mae_id)
      rescue ActiveRecord::RecordNotFound
        nil
      end
    else
      nil
    end
  end
  
  def avo_paterno(sexo_par)
    pombo_pai = self.pai
    if pombo_pai != nil
      if sexo_par == 'M'
        pombo_pai.pai
      else
        pombo_pai.mae
      end
    else
      nil
    end
  end
  
  def avo_materno(sexo_par)
    pombo_mae = self.mae
    if pombo_mae != nil
      if sexo_par == 'M'
        pombo_mae.pai
      else
        pombo_mae.mae
      end
    else
      nil
    end
  end
  
  def bisavo_paterno(sexo_par, sexo_par2)
    avo_pat = self.avo_paterno(sexo_par)
    if avo_pat != nil
      if sexo_par2 == 'M'
        avo_pat.pai
      else
        avo_pat.mae
      end
    else
      nil
    end
  end
  
  def bisavo_materno(sexo_par, sexo_par2)
    avo_mat = self.avo_materno(sexo_par)
    if avo_mat != nil
      if sexo_par2 == 'M'
        avo_mat.pai
      else
        avo_mat.mae
      end
    else
      nil
    end
  end
  
  def pai_eh_macho
    if self.pai_id != nil
      if self.pai.sexo != 'M'
        self.errors.add(:pai_id, "cannot be female")
      end
    end
  end

  def mae_eh_femea
    if self.mae_id != nil
      if self.mae.sexo != 'F'
        self.errors.add(:mae_id, "cannot be male")
      end
    end
  end
  
  def ajuste_strings
    if self.nome != nil
      self.nome.capitalize!
    end
    
    if self.anilha != nil
      self.anilha.upcase!
    end
    
  end

end

app/controllers/pombos_controller.rb
class PombosController < ApplicationController
  before_action :set_pombo, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :familia, :familia_create] #, :show
  before_action :correct_user,   only: [:edit, :update, :destroy] #, :show
  before_action :bloquear_limite, only: [:new, :create, :familia, :familia_create]
  before_action :bloquear_vencto, only: [:new, :create, :familia, :familia_create, :index, :edit]
  
  def create_titulo
    @titulo = Titulo.new(titulo_params)
    @pombo_modal = Pombo.find(@titulo.pombo_id)
    if @titulo.save
      msg = "#{t :label_premio} #{t :msg_info_criado_com_sucesso}"
      respond_to do |format|
        format.js { flash.now[:success] =  msg}
      end
    else
      render :show_modal
    end
  end
  
  def destroy_titulo
    tit = Titulo.find(params[:id])
    @pombo_modal = Pombo.find(tit.pombo_id)
    tit.destroy
    respond_to do |format|
      format.js {flash.now[:success] = t(:label_premio) + " " + t(:msg_info_excluido_com_sucesso)}
    end
  end
  
  def show_modal
    @pombo_modal = Pombo.find(params[:id])
    
    if params[:tela] == 'M'
      @tela_modal = 'modal'
    else 
      @tela_modal = 'modal_titulos'
      @titulo = Titulo.new
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  def autocomplete
    if params[:pesquisa].present?
      anilha = params[:pesquisa]
    else
      anilha = params[:pesquisa_result]
    end
    @pombos = Pombo.por_usuario(current_user.id).anilha_like(anilha)
    render json: @pombos
  end
  
  def show_modal_aplicacao
    @objeto = Pombo.find(params[:id])
    @tipo = 'P'
    respond_to do |format|
      format.js
    end
  end
  
  def gerar_aplicacao
    @msgs = Array.new
    if valida_aplicacao(params[:tratamento_id], params[:dtini_par], params[:dosagem_par], params[:medida_par])
      
      aplicacao = Aplicacao.new(pombo_id: params[:id], tratamento_id: params[:tratamento_id], dtaplicacao: params[:dtini_par], dosagem: params[:dosagem_par], medida: params[:medida_par])
      if !aplicacao.save
        respond_to do |format|
          format.js { flash.now[:danger] = aplicacao.errors }
        end
      end
      
      redirect_to pombos_path
      flash[:success] = t(:label_aplicacao) + " " + t(:msg_info_criado_com_sucesso)
    else
      respond_to do |format|
        format.js { flash.now[:danger] = @msgs }
      end
    end
  end
  
  def valida_aplicacao(tratamento, dtini, dosagem, medida)
    ok = true
    
    if tratamento.blank? 
      @msgs << "#{t :label_tratamento} #{t('errors.messages.required')}"
      ok = false
    end
    
    if dtini.blank? 
      @msgs << "#{t :label_data_inicio} #{t('errors.messages.required')}"
      ok = false
    end
    
    if dosagem.blank?
      @msgs << "#{t :label_dosagem} #{t('errors.messages.required')}"
      ok = false
    end
    
    if medida.blank?
      @msgs << "#{t :label_medida} #{t('errors.messages.required')}"
      ok = false
    end
    
    return ok
  end
  
  def familia_create
    
    @msgs = []
    
    @pomboPai = criar('pai','M', t(:label_pai), params['pai_incluir'])
    @pomboMae = criar('mae','F', t(:label_mae), params['mae_incluir'])
    @pomboFilho1 = criar('f1', nil, t(:label_filho) + ' 1', params['f1_incluir'])
    @pomboFilho2 = criar('f2', nil, t(:label_filho) + ' 2', params['f2_incluir'])
    
    if @msgs.count == 0
      pai_id = nil
      mae_id = nil
      
      if params['pai_incluir'] 
        @pomboPai.save
        pai_id = @pomboPai.id
      end
      
      if params['mae_incluir']
        @pomboMae.save
        mae_id = @pomboMae.id
      end
      
      if params['f1_incluir']
        @pomboFilho1.pai_id = pai_id
        @pomboFilho1.mae_id = mae_id
        @pomboFilho1.save
      end

      if params['f2_incluir']
        @pomboFilho2.pai_id = pai_id
        @pomboFilho2.mae_id = mae_id
        @pomboFilho2.save
      end
      
      flash[:success] = t(:label_familia) + " " + t(:msg_info_criado_com_sucesso)
      redirect_to pombos_path
    else
      render :familia
    end
    
  end
  
  def valida_membro(pombo, label)
    anilha_valid =  pombo.anilha
    if pombo.sexo.blank?
      @msgs << "<b>#{label}</b>: "
      @msgs << t(:msg_erro_campo_nao_informado, campo: t(:label_sexo))
    end
    if !pombo.valid?
      @msgs << "<b>#{label}</b>: "
      @msgs << pombo.errors.full_messages
    else
      if pombo.anilha =! nil
        p = Pombo.por_usuario(current_user.id).por_anilha(anilha_valid)
        if p.count > 0
          @msgs << "<b>#{label}</b>: "
          @msgs << t(:msg_erro_anilha_cadastrada)
        end
        pombo.anilha = anilha_valid
      end
    end
  end
  
  def criar(tipo, sexo, label, incluir)
    pombo = Pombo.new(parente_params(tipo))
    pombo.cor_id = 11 if pombo.cor_id.blank?
    pombo.usuario = current_user
    if sexo != nil
      pombo.sexo = sexo
    end
    if incluir
      valida_membro(pombo, label)
    end
    return pombo
  end
  
  def familia
    @pomboPai = Pombo.new
    @pomboMae = Pombo.new
    @pomboFilho1 = Pombo.new
    @pomboFilho2 = Pombo.new
  end
  
  def index
    user = current_user
    @pombos = Pombo.por_usuario(user).paginate(page: params[:page], :per_page => 20)
    @qtde = Pombo.por_usuario(user).count
    
    # if @pombos.size == 0
    #   redirect_to familia_path
    # end
    
    plano = user.planos.last
    flash.now[:danger] = t :msg_info_qtde_pombos_permitido, qtde: QTDE_POMBOS_BASICO if  bloqueio_por_limite_qtde(user, plano)
    
  end
  
  def filter_by
    
    vivo_par = nil
    if !params[:vivo_filter].blank?
      if params[:vivo_filter]
        vivo_par = 't'
      end
    end
    
    @pombos = Pombo.por_usuario(current_user.id).esta_vivo(vivo_par).anilha_like(params[:anilha_filter]).por_pai(params[:pai_filter],params[:pai_filter]).por_mae(params[:mae_filter],params[:mae_filter]).paginate(page: params[:page], :per_page => 20)
    
    respond_to do |format|
      format.js 
    end
    
  end

  def show
    if @pombo == nil
      redirect_to root_url
      flash[:danger] = t :msg_erro_pombo_nao_encontrado
    end
  end
  
  def new
    @pombo = Pombo.new
  end

  def edit
  end

  def create
    @pombo = Pombo.new(pombo_params)
    @pombo.usuario = current_user
    
    p = Pombo.por_usuario(current_user.id).por_anilha(@pombo.anilha)
    if p.count > 0
      flash[:danger] = t(:msg_erro_anilha_cadastrada)
      render :new 
    end
    
    if @pombo.save
      redirect_to pombos_path
      flash[:success] = t(:label_pombo) + " " + t(:msg_info_criado_com_sucesso)
    else
      render :new 
    end
  end

  def update
    
    if @pombo.update(pombo_params)
      redirect_to @pombo
      flash[:success] = t(:label_pombo) + " " + t(:msg_info_atualizado_com_sucesso)
    else
      render :edit
    end
    
  end

  def destroy
    @pombo.destroy
    redirect_to pombos_url
    flash[:success] = t(:label_pombo) + " " + t(:msg_info_excluido_com_sucesso)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pombo
      @pombo = Pombo.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pombo_params
      params.require(:pombo).permit(:anilha, :nome, :dtnasc, :sexo, :cor_id, :usuario_id, :pai_id, :mae_id, :vivo)
    end
    
    def parente_params(tipo)
      params.require(tipo).permit(:anilha, :nome, :dtnasc, :sexo, :cor_id, :vivo, :pai_id, :mae_id)
    end
    
    def titulo_params
      params.require(:titulo).permit(:nome, :ano, :pombo_id)
    end
    
    def correct_user
      @pombo = current_user.pombos.find_by(id: params[:id])
      if @pombo.nil?
        flash[:danger] = t(:msg_erro_acao_nao_permitida)
        redirect_to usuario_path(current_user)
      end
    end
    
    def bloquear_vencto
      usr = current_user
      msg =  bloqueio(usr, BLOQUEIO_PAGTO)
      if msg != ''
        flash[:danger] = t msg
        redirect_to detalhar_assinatura_usuario_path(usr)
      end
    end
    
    def bloquear_limite
      usr = current_user
      msg =  bloqueio(usr, BLOQUEIO_LIMITE_QTD)
      if msg != ''
        flash[:danger] = t(msg, go: view_context.link_to(t(:msg_erro_rever_assinatura), detalhar_assinatura_usuario_path(usr))).html_safe
        redirect_to pombos_url
      end
    end
end

app/helpers/pombos_helper.rb
module PombosHelper
  def age(dob)
    now = Time.now.utc.to_date
    ret = now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
    ret.to_i
  end
  
  def icon_pombo(sexo)
    if sexo != nil
      if sexo == 'F' || sexo == 'MAE'
        file_img = 'pombo-femea.png'
      else
        file_img = 'pombo-macho.png'
      end
      image_tag(file_img, alt: "", size: "20")
    end
  end
  
  def logo_fb
    image_tag('fb_logo.png', alt: "Compartilhe!", size: "20")
  end
  
  def logo_wz
    image_tag('whats_logo.png', alt: "Compartilhe!", size: "20")
  end
  
  def class_pombo_pais(estilo)
    estilo_classe = 'card-header small'
    if estilo == '1'
      estilo_classe
    elsif estilo == '2'
      estilo_classe += ' caixa_pai'
    elsif estilo == '3'
      estilo_classe += ' caixa_mae'
    elsif estilo == '4'
      estilo_classe += ' caixa_pai_escuro'
    elsif estilo == '5'
      estilo_classe += ' caixa_pai_claro'
    elsif estilo == '6'
      estilo_classe += ' caixa_mae_escuro'
    elsif estilo == '7'
      estilo_classe += ' caixa_mae_claro'
    end
  end
  
  def class_pombo_famila(estilo)
    estilo_classe = 'card-header small'
    if estilo == 'PAI'
      estilo_classe += ' caixa_pai'
    elsif estilo == 'MAE'
      estilo_classe += ' caixa_mae'
    else
      estilo_classe += ' bg-light'
    end
  end
  
  def pais_for_select(sexo, id)
    filtro = " usuario_id = #{current_user.id} and sexo = '#{sexo}'"
    if id != nil
       filtro += " and id not in (#{id}) "
    end
    Pombo.where(filtro).map{ |p| ["#{p.anilha} #{p.nome}", p.id]}
  end
  
  def parente_nome(pombo, tipo)
    if tipo =='P'
      if pombo.pai_id != nil && pombo.pai
        "#{pombo.pai.anilha} #{pombo.pai.nome}"
      else
        nil
      end
    else
      if pombo.mae_id != nil && pombo.mae
        "#{pombo.mae.anilha} #{pombo.mae.nome}"
      else
        nil
      end
    end
  end
  
  def ancestral_pai(pombo, n)
    if pombo == nil
      nil
    elsif n > 0 
      if pombo.pai_id == nil
        nil
      else
        ancestral_pai(pombo.pai, (n-1))
      end
    else
      if pombo.pai_id != nil
        pombo.pai
      end
    end
  end
  
  def ancestral_mae(pombo, n)
    if pombo == nil
      nil
    elsif n > 0 
      if pombo.mae_id == nil
        nil
      else
        ancestral_mae(pombo.mae, (n-1))
      end
    else
      if pombo.mae_id != nil
        pombo.mae
      end
    end
  end
  
  def titulo_panel(tipo)
    if tipo == 'PAI'
      t(:label_pai)
    elsif tipo == 'MAE'
      t(:label_mae)
    elsif tipo == 'F1'
      t(:label_filho) + ' 1'
    else
      t(:label_filho) + ' 2'
    end
  end
  
  def visivel_correct_user(id)
    pombo = current_user.pombos.find_by(id: id)
    pombo.nil?
  end
  
  def visivel(user_id)
    if current_user
      current_user.id == user_id
    else
      false
    end
  end
  
end

app/views/pombos/_caixa.html.erb
<% if pombo !=nil %>
  <div class="card">
    <div class="<%= class_pombo_pais(estilo) %>"><%= icon_pombo(pombo.sexo) %> <%= "#{pombo.anilha} #{pombo.nome}" %></div>
    <div class="card-body small">
      <%= pluralize(age(pombo.dtnasc), t(:label_ano)) if pombo.dtnasc.present? %> <%= pombo.vivo ? t(:label_vivo) : '' %>
      <% if logged_in? && !visivel_correct_user(pombo.id.to_s) %>
        <br />
        <%= link_to edit_pombo_path(pombo), class: botao_link, :title => t(:label_editar), :rel => 'tooltip', "data-placement" => "bottom" do %>
          <span class="fa fa-pencil"></span>
        <% end %>
        <%= link_to show_modal_pombos_path(id: pombo.id, tela: 'M'),  class: botao_link, remote: true, :title => t(:label_mais_info), :rel => 'tooltip', "data-placement" => "bottom" do %>
          <span class="fa fa-info-circle"></span>
        <% end %>
      <% end %>
      <%= link_to show_modal_pombos_path(id: pombo.id, tela: 'T'),  class: botao_link, remote: true, :title => t(:label_premio), :rel => 'tooltip', "data-placement" => "bottom" do %>
        <span class="fa fa-star-o"></span>
      <% end %>
    </div>
  </div>
<% elsif mostra_vazio.present? %>
  <div class="card">
    <div class="<%= class_pombo_pais(estilo) %>">
      <br /><br />
    </div>
    <div class="card-body small">
      <br /><br /><br /><br />
    </div>
  </div>
<% end %>

app/views/pombos/_lista.html.erb
<br />
<div id="lista_pombos" class="list-group">
  <% @pombos.each do |pombo| %>
    <div class="list-group-item">
      <div class="row linha-1-4">
        <div class="col-sm-4">
          <strong><%= t(:label_pombo) %></strong>: <%= link_to "#{pombo.anilha} #{pombo.nome}", edit_pombo_path(pombo) %>
        </div>
        <div class="col-sm-3">
          <strong><%= t(:label_ano) %></strong>: <%= pombo.dtnasc ? pombo.dtnasc.year : pombo.dtnasc %>
        </div>
        <div class="col-sm-3">
          <strong><%= t(:label_cor) %></strong>: <%= pombo.cor_id && pombo.cor_id != 11 ? t(pombo.cor.nome) : '' %>
        </div>
        <div class="col-sm-2">
          <strong><%= t(:label_sexo) %></strong>: <%= pombo.sexo == "F" ? t(:label_sexo_F) : t(:label_sexo_M) %>
        </div>
      </div>
      <div class="row linha-1-4">
        <div class="col-sm-6">
          <strong><%= t(:label_pai) %></strong>: <%= parente_nome(pombo,'P') %>
        </div>
        <div class="col-sm-6">
          <strong><%= t(:label_mae) %></strong>: <%= parente_nome(pombo,'M') %>
        </div>
      </div>
      
      <div class="row linha-2-0">
        <div class="col-sm-12">
          <%= link_to pombo, class: botao_link, :title => t(:label_pedigree), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-share-alt"></span>
          <% end %>
          <%= link_to edit_pombo_path(pombo), class: botao_link, :title => t(:label_editar), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to pombo, method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, :title => t(:label_excluir), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-trash"></span>
          <% end %>
          <%= link_to show_modal_pombos_path(id: pombo.id, tela: 'M'),  class: botao_link, remote: true, :title => t(:label_mais_info), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-info-circle"></span>
          <% end %>
          <%= link_to show_modal_aplicacao_pombos_path(id: pombo.id),  class: botao_link, remote: true, :title => t(:label_adicionar_compl, compl: t(:label_aplicacao)), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-flask"></span>
          <% end %>
          <%= link_to show_modal_pombos_path(id: pombo.id, tela: 'T'),  class: botao_link, remote: true, :title => t(:label_premio), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-star-o"></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="modal_pombo">
</div>

<div id="modal_gerar_tratamento">
</div>

app/views/pombos/_lista_titulos.html.erb
<table class="table table-hover" id="tabtitulo" >
  <thead>
    <tr>
      <th><%= t(:label_premio) %></th>
      <th><%= t(:label_ano) %></th>
     </tr>
  </thead>
      
  <tbody>
    <% @pombo_modal.titulos.order('ano DESC').each do |titulo| %>
      <tr>
        <td>
          <% if logged_in? && !visivel_correct_user(@pombo_modal.id.to_s) %>
            <%= link_to destroy_titulo_pombos_path(id: titulo.id), method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, remote: true, :title => t(:label_remover), :rel => 'tooltip', "data-placement" => "bottom" do %>
              <span class="fa fa-trash"></span>
            <% end %>
          <% end %>
          <%= titulo.nome %>
        </td>
        <td><%= titulo.ano %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pombos/create_titulo.js.erb
$('#tabtitulo').empty()
  .append("<%= j render partial: 'lista_titulos' %>");

<% if @titulo.valid? %>
  $("#titulo_nome").val('');
  $("#titulo_ano").val('');
  $("#collapseForm").removeClass("collapse show");
  $("#collapseForm").addClass("collapse");
  $("#modal_msg").addClass("alert alert-success");
  $("#modal_msg").html("<%= flash[:success] %>");
<% else %>
  $("#modal_msg").addClass("alert alert-danger");
  $("#modal_msg").html("<%= flash[:danger] %>");
<% end %>

app/views/pombos/edit.html.erb
<% provide(:title, t(:label_atualizar)) %>
<% provide(:button_text, t(:label_atualizar)) %>

<h4><strong><%= "#{t :label_atualizar}  #{t :label_pombo}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', pombo: @pombo %>
  </div>
</div>

<%= link_to @pombo, class: botao_link do %>
  <span class="fa fa-share-alt"></span> <%= t(:label_pedigree) %>
<% end %>
<%= link_to pombos_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/pombos/familia.html.erb
<% provide(:title, "#{t :label_cadastrar} #{t :label_familia}") %>
<% provide(:button_text, t(:label_salvar)) %>

<%= render 'shared/error_messages_flash', obj: @msgs %>

<h4><strong><%= "#{t :label_cadastrar} #{t :label_familia}" %></strong></h4>

<%= form_tag(familia_create_path, method: "post") do %>

  <div class="row">
    <div class="col-sm-6">
      <%= render 'form_familia', pombo: @pomboPai, tipo: 'PAI' %>
    </div>
    <div class="col-sm-6">
      <%= render 'form_familia', pombo: @pomboMae, tipo: 'MAE' %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-6">
      <%= render 'form_familia', pombo: @pomboFilho1, tipo: 'F1' %>
    </div>
    <div class="col-sm-6">
      <%= render 'form_familia', pombo: @pomboFilho2, tipo: 'F2' %>
    </div>
  </div>
  <br />
  <%= submit_tag yield(:button_text), class: botao_estilo %>
<% end %>
<br />
<%= link_to pombos_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/pombos/filter_by.js.erb
$("#lista_pombos").html("<%= j render partial: 'lista' %>");
$("#paginacao").html("<%= will_paginate %>");

app/views/pombos/show_modal.js.erb
$("#modal_pombo").html("<%= j render @tela_modal %>");
$('#modal_pombo_partial').modal('show'); 