config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root   'static_pages#home'
  get    '/inscrever',            to: 'usuarios#new'
  get    '/inscrever',            to: 'usuarios#create'
  get    '/login',                to: 'sessions#new'
  post   '/login',                to: 'sessions#create'
  delete '/logout',               to: 'sessions#destroy'
  get    '/faleconosco',          to: 'mensagens#new'
  post   '/faleconosco',          to: 'mensagens#create',       as: 'create_message'
  get    '/filter_by',            to: 'pombos#filter_by',       as: 'filter_by'
  get    '/familia',              to: 'pombos#familia'
  post   '/familia',              to: 'pombos#familia_create',  as: 'familia_create'
  
  resources :usuarios do
    member do
      get  :endereco
      post :salvar_endereco
      get  :editar_assinatura
      post :assinar
      get  :detalhar_assinatura
      post :cancelar_assinatura
      post :reenviar_email_ativacao
      post :alterar_tipo
      get  :visualizar_contrato
      post :aceitar_contrato
    end
    collection do
      get  :show_modal
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  resources :pombals do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
    end
  end
  resources :tratamentos do
    collection do
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      get  :show_modal
      delete :destroy_pombal_tratamento
    end
  end
  
  resources :pombos do
    collection do
      get  :autocomplete
      get  :show_modal
      post :gerar_aplicacao
      get  :show_modal_aplicacao
      post :create_titulo
      delete :destroy_titulo
    end
  end
  
  resources :competicaos do
    collection do
      get :atualiza_combo_clube
      get :modal_result
    end
    member do
      get :esquadrao
      get :esquadrao_order
    end
  end
  
  resources :provas do
    collection do
      get  :show_modal_result
      post :create_result
      delete :destroy_result
      get :recupera_desc
    end
    member do
      get  :filter_by
      get  :modal_nao_chegaram
      get  :preparar_importacao
      post  :importados
      get :modal_pp
      post :save_pp
    end
  end
  
  resources :equipes do
    member do
      get :show_modal
      post :assoc_pombo
      delete :desassoc_pombo
    end
  end
  
  resources :preparos
  resources :clubes
end

app/models/tratamento.rb
class Tratamento < ApplicationRecord
  belongs_to :usuario
  
  has_many :aplicacaos
  has_many :pombos, through: :aplicacaos
  
  has_many :pombal_tratamentos
  has_many :pombals, through: :pombal_tratamentos
  
  validates :nome,   presence: true, length: { maximum: 100 }
  validates :indicacao,   length: { maximum: 200 }
  
  scope :por_usuario, ->(par) {where("usuario_id = ?", par) if par.present? }
  
end

app/controllers/tratamentos_controller.rb
class TratamentosController < ApplicationController
  before_action :set_tratamento, only: [:show, :edit, :update, :destroy, :gerar_aplicacao]
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :show, :gerar_aplicacao]
  before_action :correct_user,   only: [:edit, :update, :show, :destroy]
  before_action :bloquear
  
  def show_modal
    @pt = PombalTratamento.find(params[:pt_id])
    @aps = Aplicacao.por_pombal_tratamento(params[:pt_id])
    respond_to do |format|
      format.js
    end
  end
  
  def destroy_pombal_tratamento
    pt = PombalTratamento.find(params[:pt_id])
    tratamento = pt.tratamento
    Aplicacao.por_pombal_tratamento(pt.id).each do |apl|
      apl.destroy
    end
    pt.destroy
    
    redirect_to tratamento
    flash[:success] = t(:label_aplicacao) + " " + t(:msg_info_excluido_com_sucesso)
  end

  def show_modal_aplicacao
    @objeto = Tratamento.find(params[:id])
    @tipo = 'T'
    respond_to do |format|
      format.js
    end
  end
  
  def gerar_aplicacao
    @msgs = Array.new
    if valida_aplicacao(params[:pombal_id], params[:dtini_par], params[:dtfim_par], params[:dosagem_par], params[:medida_par], params[:lembrar_par], params[:qtde_par], params[:intervalo_par])
      pt = PombalTratamento.new(pombal_id: params[:pombal_id], tratamento_id: params[:id], 
                           dtinicio: params[:dtini_par], dtfim: params[:dtfim_par],
                           lembrar: params[:lembrar_par], qtde: params[:qtde_par], intervalo: params[:intervalo_par])
      if !pt.save
        respond_to do |format|
          format.js { flash.now[:danger] = pt.errors }
        end
      end
      
      qtdePombos = Pombal.find(params[:pombal_id]).pombos.esta_vivo('t').count
      
      Pombal.find(params[:pombal_id]).pombos.each do |pombo|
        if pombo.vivo
          aplicacao = Aplicacao.new(pombo_id: pombo.id, tratamento_id: params[:id], dtaplicacao: params[:dtini_par], dosagem: (params[:dosagem_par].to_f/qtdePombos.to_f), medida: params[:medida_par], pt_id: pt.id )
          if !aplicacao.save
            respond_to do |format|
              format.js { flash.now[:danger] = aplicacao.errors }
            end
          end
        end
      end
      
      redirect_to pt.tratamento
      flash[:success] = t(:label_aplicacao) + " " + t(:msg_info_criado_com_sucesso)
    else
      respond_to do |format|
        format.js { flash.now[:danger] = @msgs }
      end
    end
  end
  
  def valida_aplicacao(pombal, dtini, dtfim, dosagem, medida, lembrar, qtde, intervalo)
    ok = true
    if pombal.blank? 
      @msgs << "#{t :label_pombal} #{t('errors.messages.required')}"
      ok = false
    end
    if dtini.blank? 
      @msgs << "#{t :label_data_inicio} #{t('errors.messages.required')}"
      ok = false
    end
    
    if !dtini.blank? && !dtfim.blank? && dtini > dtfim
      @msgs << "#{t :label_data_fim} #{t('errors.messages.greater_than', count: t(:label_data_inicio))}"
      ok = false
    end
    
    if dosagem.blank?
      @msgs << "#{t :label_dosagem} #{t('errors.messages.required')}"
      ok = false
    end
    
    if medida.blank?
      @msgs << "#{t :label_medida} #{t('errors.messages.required')}"
      ok = false
    end
    
    if !lembrar.blank? && lembrar
      if qtde.blank? 
        @msgs << "#{t :label_qtde} #{t('errors.messages.required')}"
        ok = false
      end
      
      if intervalo.blank? 
        @msgs << "#{t :label_intervalo} #{t('errors.messages.required')}"
        ok = false
      end
    end
    
    return ok
  end
  
  # GET /tratamentos
  def index
    @tratamentos = Tratamento.por_usuario(current_user.id)
  end

  # GET /tratamentos/1
  def show
  end

  # GET /tratamentos/new
  def new
    @tratamento = Tratamento.new
  end

  # GET /tratamentos/1/edit
  def edit
  end

  # POST /tratamentos
  def create
    @tratamento = Tratamento.new(tratamento_params)
    @tratamento.usuario = current_user
    if @tratamento.save
      redirect_to tratamentos_path
      flash[:success] = t(:label_tratamento) + " " + t(:msg_info_criado_com_sucesso)
    else
      render :new
    end
  end

  # PATCH/PUT /tratamentos/1
  def update
    if @tratamento.update(tratamento_params)
      redirect_to @tratamento
      flash[:success] = t(:label_tratamento) + " " + t(:msg_info_atualizado_com_sucesso)
    else
      render :edit
    end
  end

  # DELETE /tratamentos/1
  def destroy
    @tratamento.pombos.delete_all
    @tratamento.pombals.delete_all
    @tratamento.destroy
    redirect_to tratamentos_url
    flash[:success] = t(:label_tratamento) + " " + t(:msg_info_excluido_com_sucesso)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tratamento
      @tratamento = Tratamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tratamento_params
      params.require(:tratamento).permit(:nome, :indicacao, :lembrar, :qtde, :intervalo)
    end
    
    def correct_user
      @tratamento = current_user.tratamentos.find_by(id: params[:id])
      if @tratamento.nil?
        flash[:danger] = t(:msg_erro_acao_nao_permitida)
        redirect_to usuario_path(current_user)
      end
    end
    
    def bloquear
      usr = current_user
      msg =  bloqueio(usr, BLOQUEIO_PAGTO)
      if msg != ''
        flash[:danger] = t msg
        redirect_to detalhar_assinatura_usuario_path(usr)
      end
    end
end

app/helpers/tratamentos_helper.rb
module TratamentosHelper
end

app/views/tratamentos/_form.html.erb
<%= form_for(tratamento) do |f| %>
  <%= render 'shared/error_messages', obj: tratamento %>
  
  <div class="form-group">
    <%= f.label t :label_nome %>
    <%= f.text_field :nome, class: 'form-control', required: true %>
  </div>
  
  <div class="form-group">
    <%= f.label t :label_indicacao %>
    <%= f.text_area :indicacao, class: 'form-control' %>
  </div>
  <%= f.submit yield(:button_text), class: botao_estilo %>
  <br /><br />
  
<% end %>

app/views/tratamentos/_modal.html.erb
<!-- https://www.mirceasamuila.com/posts/bootstrap-modals-in-rails -->
<div id="modal_pombo_partial" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header bg-light">
        <h4 class="modal-title"><%= "#{t :label_tratamento}: #{@pt.tratamento.nome}" %></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      
      <div class="modal-body">
        <strong><%= t(:msg_info_pombos_que_receberam_aplicacao_de_em, nome: @pt.tratamento.nome, data: @pt.dtinicio.strftime(mask_data_ruby)) %></strong>
        <br /><br />
        <table class="table table-hover">
          <thead>
            <tr>
              <th><%= t(:label_pombo) %></th>
              <th><%= t(:label_dosagem) %></th>
             </tr>
          </thead>
              
          <tbody>
            <% @aps.each do |ap| %>
              <tr>
                <td><%= "#{ap.pombo.anilha} #{ap.pombo.nome}" %></td>
                <td><%= "#{number_with_precision(ap.dosagem, precision: 3) } " + ' ' + t('label_medida_'+ ap.medida) if !ap.medida.blank? %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <p class="text-right" ><%= "Dosagem total: #{number_with_precision(@aps.to_a.sum(&:dosagem), :precision => 3)} #{ t('label_medida_'+ @aps.first.medida)}" if @aps.to_a.sum(&:dosagem) > 0 %></p>
      </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal"><%= t(:label_fechar) %></button>
      </div>
      
    </div>
  </div>
</div>

app/views/tratamentos/edit.html.erb
<% provide(:title, t(:label_atualizar)) %>
<% provide(:button_text, t(:label_atualizar)) %>

<h4><strong><%= "#{t :label_atualizar}  #{t :label_tratamento}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', tratamento: @tratamento %>
  </div>
</div>

<%= link_to tratamentos_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/tratamentos/gerar_aplicacao.js.erb
$("#modal_gerar_erro").addClass("alert alert-danger");
$("#modal_gerar_erro").html("<%= flash[:danger] %>");

app/views/tratamentos/index.html.erb
<% provide(:title, t(:label_lista_tratamentos)) %>
<h4><strong><%= t :label_lista_tratamentos %></strong></h4>

<%= link_to new_tratamento_path, class: botao_link do %>
  <span class="fa fa-plus"></span> <%= "#{t :label_cadastrar} #{t :label_tratamento}" %>
<% end %>
<br /><br />

<div id="lista_pombal" class="list-group">
  <% @tratamentos.each do |tratamento| %>
    <div class="list-group-item">
      <div class="row linha-1-4">
        <div class="col-sm-3">
          <strong><%= t(:label_nome) %></strong>: <%= link_to tratamento do %><%= tratamento.nome %><% end %>
        </div>
        <div class="col-sm-9">
          <strong><%= t(:label_indicacao) %></strong>: <%= tratamento.indicacao %>
        </div>
      </div>
      <div class="row linha-2-0">
        <div class="col-sm-12">
          <%= link_to edit_tratamento_path(tratamento), class: botao_link, :title => t(:label_editar), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-pencil"></span>
          <% end %>
          <%= link_to tratamento, method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, :title => t(:label_excluir), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-trash"></span>
          <% end %>
          <%= link_to show_modal_aplicacao_tratamentos_path(id: tratamento.id),  class: botao_link, remote: true, :title => t(:label_aplicar_compl, compl: t(:label_pombal)), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-flask"></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id="modal_gerar_tratamento">
</div>

app/views/tratamentos/new.html.erb
<% provide(:title, "#{t :label_cadastrar} #{t :label_tratamento}") %>
<% provide(:button_text, t(:label_salvar)) %>

<h4><strong><%= "#{t :label_cadastrar} #{t :label_tratamento}" %></strong></h4>

<div class="row">
  <div class="col-md-6 ml-md-auto mr-md-auto">
    <%= render 'form', tratamento: @tratamento %>
  </div>
</div>

<%= link_to tratamentos_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:cancelar) %>
<% end %>

app/views/tratamentos/show.html.erb
<% provide(:title, @tratamento.nome) %>

<p>
  <h4>
    <strong><%= "#{t :label_tratamento}:  #{@tratamento.nome}" %></strong>
  </h4>
  <% if @tratamento.indicacao.present? %>
    <strong><%= "#{t :label_indicacao}: " %></strong><%= @tratamento.indicacao %>
    <br /><br />
  <% end %>
  
  <%= link_to show_modal_aplicacao_tratamentos_path(id: @tratamento.id),  class: botao_link, remote: true do %>
    <span class="fa fa-flask"></span> <%= "#{t :label_gerar} #{t :label_aplicacao}" %>
  <% end %>
</p>

<div id="lista_aplicacoes" class="list-group">

  <% @tratamento.pombal_tratamentos.order('dtinicio DESC').each do |pt| %>
    <div class="list-group-item">
      <div class="row linha-1-4">
        <div class="col-sm-4">
          <strong><%= t(:label_pombal) %></strong>: <%= pt.pombal.nome %>
        </div>
        <div class="col-sm-2">
          <strong><%= t(:label_data_inicio) %></strong>: <%= pt.dtinicio.strftime(mask_data_ruby) if pt.dtinicio? %>
        </div>
        <div class="col-sm-2">
          <strong><%= t(:label_data_fim) %></strong>: <%= pt.dtfim.strftime(mask_data_ruby) if pt.dtfim? %>
        </div>
        <div class="col-sm-4">
          <strong><%= t(:label_dosagem_por_pombal) %></strong>: <%= "#{number_with_precision(Aplicacao.por_pombal_tratamento(pt.id).to_a.sum(&:dosagem), precision: 3) } "%>
          <!--  + ' ' + t('label_medida_'+ pt.medida) if !pt.medida.blank? -->
        </div>
      </div>
      <div class="row linha-2-0">
        <div class="col-sm-12">
          <%= link_to show_modal_tratamentos_path(pt_id: pt.id),  class: botao_link, remote: true, :title => t(:label_mais_info), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-info-circle"></span>
          <% end %>
          
          <%= link_to destroy_pombal_tratamento_tratamentos_path(pt_id: pt.id), method: :delete, data: { confirm: t(:msg_quest_apagar_padrao) }, class: botao_link, :title => t(:label_excluir), :rel => 'tooltip', "data-placement" => "bottom" do %>
            <span class="fa fa-trash"></span>
          <% end %>
          
        </div>
      </div>
    </div>
  <% end %>

</div>

<%= link_to tratamentos_path, class: botao_link do %>
  <span class="fa fa-caret-left"></span> <%= t(:label_voltar) %>
<% end %>

<div id="modal_pombo">
</div>

<div id="modal_gerar_tratamento">
</div>

app/views/tratamentos/show_modal.js.erb
$("#modal_pombo").html("<%= j render "modal"%>");
$('#modal_pombo_partial').modal('show'); 

app/views/tratamentos/show_modal_aplicacao.js.erb
$("#modal_gerar_tratamento").html("<%= j render "shared/modal_gerar"%>");
$('#modal_gerar_tratamento_partial').modal('show'); 